version: '3.8'

x-common-variables: &common-variables
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  REDIS_PASSWORD: ${REDIS_PASSWORD}

services:
  postgres:
    image: postgres:15-alpine
    container_name: vandine_postgres
    environment:
      <<: *common-variables
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    # Resource limits for Pi
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  redis:
    image: redis:7-alpine
    container_name: vandine_redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile.pi
    container_name: vandine_django
    environment:
      <<: *common-variables
      DJANGO_SETTINGS_MODULE: vandine_monitor.settings
    volumes:
      - ./src/django_app:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    # Use fewer workers on Pi
    command: gunicorn vandine_monitor.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 120
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  fastapi:
    build:
      context: .
      dockerfile: docker/fastapi/Dockerfile.pi
    container_name: vandine_fastapi
    environment:
      <<: *common-variables
    volumes:
      - ./src/fastapi_app:/app
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    # Single worker for Pi
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --workers 1
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  celery:
    build:
      context: .
      dockerfile: docker/django/Dockerfile.pi
    container_name: vandine_celery
    environment:
      <<: *common-variables
    volumes:
      - ./src/django_app:/app
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    command: celery -A vandine_monitor worker -l info --concurrency=2
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  celery-beat:
    build:
      context: .
      dockerfile: docker/django/Dockerfile.pi
    container_name: vandine_celery_beat
    environment:
      <<: *common-variables
    volumes:
      - ./src/django_app:/app
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    command: celery -A vandine_monitor beat -l info
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  nginx:
    image: nginx:1.25-alpine
    container_name: vandine_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/static
      - media_volume:/media
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django
      - fastapi
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

volumes:
  postgres_data:
  static_volume:
  media_volume: