#!/bin/bash

echo "======================================"
echo "Push to GitHub using HTTPS"
echo "======================================"
echo ""
echo "To push your code, you need a GitHub Personal Access Token:"
echo ""
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token (classic)'"
echo "3. Name it: 'vandine-network-monitor-push'"
echo "4. Select scopes: 'repo' (all repo permissions)"
echo "5. Click 'Generate token' and COPY IT"
echo ""
echo "Then run this command:"
echo "git push -u origin main"
echo ""
echo "When prompted:"
echo "Username: jag18729"
echo "Password: [paste your token here]"
echo ""
echo "Note: The token won't be visible when you paste it."
echo ""
echo "Repository URL: https://github.com/jag18729/vandine-network-monitor"
