#!/bin/bash

# Instructions to create and push to GitHub repository
echo "======================================"
echo "GitHub Repository Setup Instructions"
echo "======================================"
echo ""
echo "1. First, create a new repository on GitHub:"
echo "   - Go to https://github.com/new"
echo "   - Name it: vandine-network-monitor"
echo "   - Description: Network Engineering Lab - Production infrastructure showcase"
echo "   - Keep it public or private as you prefer"
echo "   - DO NOT initialize with README (we already have one)"
echo "   - Click 'Create repository'"
echo ""
echo "2. After creating the repository, run these commands:"
echo ""
echo "# Add your GitHub repository as origin (replace YOUR_USERNAME with your GitHub username)"
echo "git remote add origin https://github.com/YOUR_USERNAME/vandine-network-monitor.git"
echo ""
echo "# Or if using SSH:"
echo "git remote add origin git@github.com:YOUR_USERNAME/vandine-network-monitor.git"
echo ""
echo "# Push the code to GitHub"
echo "git push -u origin main"
echo ""
echo "3. Your repository will be live at:"
echo "   https://github.com/YOUR_USERNAME/vandine-network-monitor"
echo ""
echo "======================================"
echo "Repository Contents:"
echo "======================================"
echo ""
echo "Main Files:"
ls -la vandine-showcase.html README.md .gitignore 2>/dev/null
echo ""
echo "Current Git Status:"
git status --short
echo ""
echo "Latest Commit:"
git log --oneline -1
