name: Network Monitor Health Check

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:  # Allow manual trigger
  push:
    branches:
      - main

jobs:
  health-check:
    name: Check Infrastructure Health
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Check Cloudflare CDN
        run: |
          echo "Testing Cloudflare edge network..."
          # Test Cloudflare trace
          response=$(curl -s https://www.cloudflare.com/cdn-cgi/trace | head -5)
          if [ -n "$response" ]; then
            echo "✅ Cloudflare accessible"
            echo "$response"
          else
            echo "❌ Cloudflare check failed"
            exit 1
          fi
      
      - name: Validate HTML files
        run: |
          echo "Validating project HTML files..."
          for file in *.html; do
            if [ -f "$file" ]; then
              echo "Checking $file..."
              # Basic validation
              grep -q "<!DOCTYPE" "$file" && echo "  ✅ Valid DOCTYPE" || echo "  ⚠️ Missing DOCTYPE"
            fi
          done
      
      - name: Check project structure
        run: |
          echo "Verifying project structure..."
          echo "📁 Project files:"
          ls -la *.html *.md 2>/dev/null | head -10
          echo ""
          echo "📊 Repository stats:"
          echo "Total HTML files: $(find . -name '*.html' | wc -l)"
          echo "Total size: $(du -sh . | cut -f1)"
      
      - name: Create status badge
        run: |
          echo "Status check complete at $(date)"
          echo "::notice title=Health Check::All systems operational"
